"""
=============================================================================
DJANGO SETTINGS FILE - ShopEase E-Commerce Platform
=============================================================================

This file controls every aspect of your Django project. Think of it as the
control panel for your entire application.

Generated by 'django-admin startproject' using Django 6.0.

Official Django settings documentation:
https://docs.djangoproject.com/en/6.0/topics/settings/

Full list of all available settings:
https://docs.djangoproject.com/en/6.0/ref/settings/

IMPORTANT: This is a development configuration. Never use these settings
in production! They're insecure by design for easier local development.
"""

# =============================================================================
# IMPORTS - Libraries we need for configuration
# =============================================================================

from pathlib import Path  # Modern Python way to handle file paths (better than os.path)
import os  # Operating system interface - needed for some legacy path operations


# =============================================================================
# BASE DIRECTORY - Where is this project located?
# =============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'
#
# __file__ = current file (settings.py)
# .resolve() = get absolute path (no ../.. nonsense)
# .parent = go up one folder (to shopease_project folder)
# .parent.parent = go up another folder (to main project root)
#
# If settings.py is at: /home/user/ShopEase/shopease/shopease_project/settings.py
# Then BASE_DIR will be: /home/user/ShopEase/shopease/
#
# Why? So we can reference other folders like: BASE_DIR / 'templates'
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY SETTINGS - Critical for protecting your application
# =============================================================================

# SECRET_KEY: Used for cryptographic signing
# - Encrypts sessions (user login data)
# - Signs cookies and tokens
# - Generates CSRF tokens
# - Creates password reset links
#
# CRITICAL: Change this in production! Keep it secret!
# Generate a new one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
SECRET_KEY = 'django-insecure-hpo_al!uz*yajcnkfc0!-x-w-6!p!3ep77qtkd4da_+0fubei1'

# DEBUG: Shows detailed error pages with full traceback
#
# When True (development):
# - Shows detailed error pages when things break (helpful for debugging)
# - Serves static files automatically
# - Displays SQL queries being run
# - Shows all settings and variables in error reports
#
# When False (production):
# - Shows generic "Server Error" page
# - Never shows sensitive information
# - Logs errors to file instead
#
# NEVER set DEBUG=True in production! It exposes secrets!
DEBUG = True

# ALLOWED_HOSTS: Which domain names can access this site?
#
# Empty list [] means only localhost/127.0.0.1 can access (good for development)
# In production, set to: ['yourwebsite.com', 'www.yourwebsite.com']
#
# Why? Prevents HTTP Host Header attacks where hackers try to trick
# your server into generating malicious links
ALLOWED_HOSTS = []


# =============================================================================
# INSTALLED APPS - All the "modules" that make up your project
# =============================================================================

INSTALLED_APPS = [
    # DJANGO'S BUILT-IN APPS (come with Django):
    # These provide essential functionality out of the box

    'django.contrib.admin',        # Admin interface at /admin/ - manage your data with UI
    'django.contrib.auth',         # User authentication - login, logout, permissions
    'django.contrib.contenttypes', # Tracks all models in your project (needed by auth)
    'django.contrib.sessions',     # Session management - remembers users between requests
    'django.contrib.messages',     # One-time notifications ("Product added to cart!")
    'django.contrib.staticfiles',  # Serves CSS, JavaScript, images in development

    # YOUR CUSTOM APPS (the ones you created):
    # Each app handles a specific part of your e-commerce site

    'accounts',      # User management (customers, sellers, admins)
    'products',      # Product catalog (products, categories, images)
    'orders',        # Order processing (customer orders, order items)
    'cart',          # Shopping cart (add/remove products before checkout)
    'admin_panel',   # Custom admin dashboard (analytics, reports)
]

# AUTH_USER_MODEL: Which model represents a user?
#
# By default, Django uses its built-in User model
# We're telling it to use our custom User model from the accounts app
#
# Format: 'app_name.ModelName'
# This gives us flexibility to add custom fields like:
# - role (customer, seller, admin)
# - phone number
# - address
# - profile picture
AUTH_USER_MODEL = 'accounts.User'


# =============================================================================
# MIDDLEWARE - Request/Response processing pipeline
# =============================================================================

# Think of middleware as a series of checkpoints every request passes through:
#
# REQUEST comes in → Middleware 1 → Middleware 2 → ... → Your View
# Your View responds → ... → Middleware 2 → Middleware 1 → RESPONSE goes out
#
# Order matters! Each one processes the request before passing it to the next

MIDDLEWARE = [
    # SecurityMiddleware: Adds security headers to responses
    # - X-Content-Type-Options (prevent MIME sniffing attacks)
    # - X-Frame-Options (prevent clickjacking)
    # - Strict-Transport-Security (force HTTPS)
    'django.middleware.security.SecurityMiddleware',

    # SessionMiddleware: Manages sessions (login state, shopping cart)
    # - Creates session cookie when user visits
    # - Loads session data from database/cache
    # - Makes request.session available in views
    'django.contrib.sessions.middleware.SessionMiddleware',

    # CommonMiddleware: General-purpose request processing
    # - Handles URL redirects (www.site.com → site.com)
    # - Sets Content-Length header
    # - Handles ETags for caching
    # - Forbids access to User-Agents in DISALLOWED_USER_AGENTS
    'django.middleware.common.CommonMiddleware',

    # CsrfViewMiddleware: Protects against Cross-Site Request Forgery
    # - Generates CSRF token for forms
    # - Validates token on POST/PUT/DELETE requests
    # - Blocks requests with invalid/missing tokens
    # This prevents attackers from tricking users into submitting forms
    'django.middleware.csrf.CsrfViewMiddleware',

    # AuthenticationMiddleware: Associates requests with users
    # - Loads user from session
    # - Makes request.user available in views
    # - Sets request.user to AnonymousUser if not logged in
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # MessageMiddleware: Handles one-time messages
    # - "Successfully added to cart!"
    # - "Login required to checkout"
    # - Makes request._messages available
    'django.contrib.messages.middleware.MessageMiddleware',

    # ClickjackingMiddleware: Prevents your site from being framed
    # - Sets X-Frame-Options header
    # - Stops attackers from embedding your site in <iframe>
    # - Prevents UI redressing attacks
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =============================================================================
# URL CONFIGURATION - Where to find URL routing
# =============================================================================

# ROOT_URLCONF: The main URLs file
#
# Django starts here when routing a request to a view
# Format: 'project_name.urls'
#
# This file contains all the main URL patterns and includes
# URL patterns from individual apps
ROOT_URLCONF = 'shopease_project.urls'


# =============================================================================
# TEMPLATES - HTML template engine configuration
# =============================================================================

TEMPLATES = [
    {
        # BACKEND: Which template engine to use?
        # Django comes with Jinja2 and its own DjangoTemplates engine
        # DjangoTemplates is simpler and perfectly fine for most projects
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # DIRS: Where to look for template files?
        # List of directories Django searches for templates IN ORDER
        #
        # os.path.join(BASE_DIR, 'templates') means:
        # Look in the 'templates' folder at project root
        #
        # Django will search here FIRST, then in app-level template folders
        # This lets you override app templates with project-level ones
        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        # APP_DIRS: Should Django look in each app's 'templates' folder?
        # True means Django automatically finds templates like:
        # products/templates/products/product_list.html
        # accounts/templates/accounts/login.html
        #
        # This is why we use app_name/template_name.html structure
        'APP_DIRS': True,

        # OPTIONS: Extra settings for template rendering
        'OPTIONS': {
            # context_processors: Functions that add variables to EVERY template
            # These variables are available in all templates automatically
            'context_processors': [
                # Makes 'request' variable available in templates
                # Useful for: request.user, request.path, request.GET
                'django.template.context_processors.request',

                # Makes 'user' and 'perms' available in templates
                # user = currently logged in user (or AnonymousUser)
                # perms = user permissions (for checking admin access)
                'django.contrib.auth.context_processors.auth',

                # Makes 'messages' available in templates
                # For displaying flash messages like "Product added!"
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =============================================================================
# WSGI APPLICATION - Entry point for web servers
# =============================================================================

# WSGI (Web Server Gateway Interface): How web servers talk to Django
#
# In production, web servers (Apache, Nginx) use WSGI to communicate
# with your Django app. This setting tells them where to find the
# WSGI application object.
#
# Format: 'project_name.wsgi.application'
WSGI_APPLICATION = 'shopease_project.wsgi.application'


# =============================================================================
# DATABASE - Where to store data
# =============================================================================

DATABASES = {
    # 'default': The primary database (you can have multiple databases)
    'default': {
        # ENGINE: Which database system?
        # - 'django.db.backends.sqlite3' = SQLite (file-based, perfect for development)
        # - 'django.db.backends.postgresql' = PostgreSQL (powerful, production-ready)
        # - 'django.db.backends.mysql' = MySQL
        # - 'django.db.backends.oracle' = Oracle
        #
        # SQLite is great for development because:
        # - No installation needed
        # - No server to run
        # - Just a single file
        # - Fast for small datasets
        'ENGINE': 'django.db.backends.sqlite3',

        # NAME: Database file location (for SQLite)
        # BASE_DIR / 'db.sqlite3' creates the file in your project root
        #
        # For PostgreSQL/MySQL, NAME would be the database name:
        # 'NAME': 'shopease_db'
        'NAME': BASE_DIR / 'db.sqlite3',

        # For PostgreSQL/MySQL, you'd also need:
        # 'USER': 'your_db_user',
        # 'PASSWORD': 'your_db_password',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
    }
}


# =============================================================================
# PASSWORD VALIDATION - Enforce strong passwords
# =============================================================================

# These validators run when users set passwords (signup, password change)
# Each validator checks for a different weakness

AUTH_PASSWORD_VALIDATORS = [
    {
        # UserAttributeSimilarityValidator: Password shouldn't be similar to username/email
        # Rejects: username="john", password="john123"
        # Accepts: username="john", password="SecureP@ss2024"
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # MinimumLengthValidator: Password must be at least 8 characters
        # Rejects: "pass123" (7 chars)
        # Accepts: "password123" (11 chars)
        # You can customize: MinimumLengthValidator(min_length=12)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # CommonPasswordValidator: Rejects commonly used passwords
        # Has a list of 20,000+ common passwords (password123, qwerty, etc.)
        # Rejects: "password", "12345678", "qwerty"
        # Accepts: "MyUn1qu3P@ssw0rd"
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # NumericPasswordValidator: Password can't be entirely numeric
        # Rejects: "123456789", "987654321"
        # Accepts: "pass123word" (has letters too)
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================================================================
# INTERNATIONALIZATION (i18n) - Language and timezone settings
# =============================================================================

# LANGUAGE_CODE: Default language for the site
# Format: language-country (en-us, es-es, fr-fr, hi-in)
# Affects:
# - Django admin interface language
# - Date/time formatting
# - Number formatting
# - Error messages
LANGUAGE_CODE = 'en-us'

# TIME_ZONE: Which timezone for date/time display?
# 'UTC' = Coordinated Universal Time (standard)
# Others: 'Asia/Kolkata', 'America/New_York', 'Europe/London'
#
# Django stores all times in UTC in database, then converts
# to this timezone when displaying to users
TIME_ZONE = 'UTC'

# USE_I18N: Enable internationalization?
# True = Django's translation system is active
# Allows you to translate your site to multiple languages
#
# With this enabled, you can use:
# from django.utils.translation import gettext as _
# message = _("Hello")  # Will show "Hola" in Spanish, etc.
USE_I18N = True

# USE_TZ: Use timezone-aware datetimes?
# True = All datetimes are stored with timezone info (recommended!)
# False = Naive datetimes (no timezone info)
#
# Always leave this True! It prevents bugs with daylight saving
# and international users
USE_TZ = True


# =============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# =============================================================================

# STATIC_URL: URL prefix for static files
# When template has: <link href="{% static 'css/style.css' %}">
# Browser loads: http://localhost:8000/static/css/style.css
#
# The '/static/' is what you set here
STATIC_URL = 'static/'

# STATIC_ROOT: Where to collect all static files for production
# When you run 'python manage.py collectstatic', all static files
# from all apps get copied here
#
# In production, your web server (Nginx/Apache) serves files from here
# Format: /path/to/project/staticfiles/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STATICFILES_DIRS: Additional directories with static files
# Django looks in these folders for static files DURING DEVELOPMENT
#
# Structure:
# static/
#   css/
#     style.css
#   js/
#     script.js
#   images/
#     logo.png
#
# In templates: {% load static %}
#               <img src="{% static 'images/logo.png' %}">
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# =============================================================================
# MEDIA FILES (User-uploaded content)
# =============================================================================

# MEDIA_URL: URL prefix for user-uploaded files
# When template has: <img src="{{ product.image.url }}">
# Browser loads: http://localhost:8000/media/products/image.jpg
MEDIA_URL = '/media/'

# MEDIA_ROOT: Where to store user-uploaded files
# When user uploads product image, it's saved in:
# /path/to/project/media/products/image.jpg
#
# Structure:
# media/
#   products/       (from ProductImage model: upload_to='products/')
#     product1.jpg
#     product2.jpg
#   categories/     (from Category model: upload_to='categories/')
#     electronics.jpg
#   profiles/       (from user profiles)
#     user1.jpg
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# =============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# =============================================================================

# DEFAULT_AUTO_FIELD: What type of auto-generated ID to use?
# 'BigAutoField' = 64-bit integer (supports IDs up to 9 quintillion)
# 'AutoField' = 32-bit integer (supports IDs up to 2 billion)
#
# BigAutoField is the modern default. Use it unless you have a specific
# reason to use the smaller AutoField.
#
# This affects models without explicit primary key:
# class Product(models.Model):
#     name = models.CharField(max_length=200)
#     # Django automatically adds: id = models.BigAutoField(primary_key=True)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# ADDITIONAL NOTES FOR LEARNING
# =============================================================================

"""
DEVELOPMENT vs PRODUCTION SETTINGS:

This file is for DEVELOPMENT. In production, you should:

1. Set DEBUG = False
   - Never expose error details to users

2. Change SECRET_KEY
   - Generate a new random secret key
   - Store it in environment variable, not in code

3. Set ALLOWED_HOSTS
   - ALLOWED_HOSTS = ['yourwebsite.com', 'www.yourwebsite.com']

4. Use production database
   - PostgreSQL instead of SQLite

5. Configure static/media file serving
   - Use WhiteNoise or CDN, not Django

6. Add security headers
   - SECURE_SSL_REDIRECT = True
   - SESSION_COOKIE_SECURE = True
   - CSRF_COOKIE_SECURE = True

7. Set up logging
   - Log errors to files, not console

8. Use environment variables for secrets
   - SECRET_KEY = os.environ.get('SECRET_KEY')
   - Database passwords
   - API keys

COMMON SETTINGS TO ADD AS YOUR PROJECT GROWS:

- CACHES: Configure Redis/Memcached for caching
- EMAIL_BACKEND: For sending emails (order confirmations, etc.)
- LOGGING: Configure logging for debugging and monitoring
- REST_FRAMEWORK: If adding API endpoints
- CELERY_*: If adding background tasks
- PAYMENT_*: Payment gateway credentials (Stripe, PayPal, etc.)

Each setting has a purpose. Don't change things randomly!
Read the docs: https://docs.djangoproject.com/en/6.0/ref/settings/
"""
