# Generated by Django 5.0.1 on 2026-01-10 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-added_at']},
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_active_user_cart',
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_active_session_cart',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_user_id_5d777a_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_session_3c25be_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_updated_c46eb6_idx',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_cart_user_id_b645f9_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='cart_cart_session_5e1af5_idx'),
        ),
    ]
