# Generated by Django 5.2.4 on 2026-01-09 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Phone number with country code', max_length=15, null=True)),
                ('shipping_address_line1', models.CharField(blank=True, help_text='Street address, P.O. box', max_length=200, null=True)),
                ('shipping_address_line2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor', max_length=200, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_country', models.CharField(blank=True, default='India', max_length=100)),
                ('billing_same_as_shipping', models.BooleanField(default=True, help_text='Use shipping address for billing')),
                ('billing_address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_country', models.CharField(blank=True, default='India', max_length=100)),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/')),
                ('newsletter_subscribed', models.BooleanField(default=False, help_text='Receive promotional emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['user'], name='accounts_pr_user_id_97e401_idx')],
            },
        ),
    ]
