# Generated by Django 6.0 on 2025-12-20 09:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, help_text='Unique order identifier', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current order status', max_length=20)),
                ('shipping_name', models.CharField(help_text='Full name for delivery', max_length=200)),
                ('shipping_address', models.TextField(help_text='Complete shipping address')),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_zip_code', models.CharField(max_length=20)),
                ('shipping_country', models.CharField(default='India', max_length=100)),
                ('shipping_phone', models.CharField(help_text='Contact number for delivery', max_length=20)),
                ('shipping_email', models.EmailField(help_text='Email for order updates', max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all items before tax and shipping', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Shipping charges', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Final amount charged to customer', max_digits=10)),
                ('payment_method', models.CharField(default='COD', help_text='Payment method (COD, Card, UPI, etc.)', max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100)),
                ('customer_notes', models.TextField(blank=True, help_text='Special instructions from customer')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to customer)')),
                ('tracking_number', models.CharField(blank=True, help_text='Shipping carrier tracking number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When order was placed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification time')),
                ('shipped_at', models.DateTimeField(blank=True, help_text='When order was shipped', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When order was delivered', null=True)),
                ('user', models.ForeignKey(help_text='Customer who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name at time of purchase', max_length=200)),
                ('product_sku', models.CharField(blank=True, help_text='Product SKU at time of purchase', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of purchase', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(default=1, help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(help_text='Product purchased', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
    ]
