"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# Replace hardcoded SECRET_KEY
SECRET_KEY = config('SECRET_KEY')

# Replace hardcoded DEBUG
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []


# Application definition

# Open config/settings.py
# Find INSTALLED_APPS (around line 33)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Our apps
    'apps.products',
    'apps.core',
    'apps.cart',
    'apps.accounts',
    'apps.orders',
    'apps.admin_panel',  # Custom admin panel with role-based access
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.admin_panel.middleware.ProductViewTrackingMiddleware',  # Product analytics tracking
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.admin_panel.context_processors.admin_permissions',  # Admin permissions
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Update DATABASES
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# # Password validation
# # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# URL to use when referring to static files located in STATIC_ROOT
STATIC_URL = '/static/'

# Absolute filesystem path to directory for collected static files
# This is where 'python manage.py collectstatic' copies files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional locations of static files
# Django will look for static files in these directories
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# SESSION CONFIGURATION - Shopping Cart
# ==========================================

# Where to store sessions
# Options: 'django.contrib.sessions.backends.db' (database)
#         'django.contrib.sessions.backends.cache' (Redis/Memcached)
#         'django.contrib.sessions.backends.file' (filesystem)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Session cookie settings
SESSION_COOKIE_NAME = 'shopease_sessionid'  # Cookie name (default: sessionid)
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds (how long cart persists)
SESSION_COOKIE_HTTPONLY = True  # JavaScript can't access (prevents XSS)
SESSION_COOKIE_SECURE = False  # Set True in production (HTTPS only)
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection (Lax or Strict)

# Save session on every request (updates expiry)
# False = only saves when session is modified
SESSION_SAVE_EVERY_REQUEST = False

# Clear expired sessions regularly
# Run: python manage.py clearsessions (add to cron job)

# ==========================================
# AUTHENTICATION SETTINGS
# ==========================================

# Custom authentication backends (allows login with email OR username)
# Multiple backends are tried in order until one succeeds
AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.EmailOrUsernameBackend',  # Try email/username first
    'django.contrib.auth.backends.ModelBackend',      # Fallback to default
]

# Where to redirect after login/logout
LOGIN_URL = '/accounts/login/'  # Where to redirect if @login_required
LOGIN_REDIRECT_URL = '/'  # After successful login
LOGOUT_REDIRECT_URL = '/'  # After logout

# Password validation
# Makes passwords secure (min length, not common, not all numeric)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        # Prevents: username=john, password=john123
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Minimum 8 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        # Prevents: password123, qwerty, etc.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        # Prevents: 12345678 (all numbers)
    },
]

# Email backend (for password reset)
# Development: Console backend (prints emails to terminal)
# Production: SMTP backend (sends real emails)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production email settings (configure when deploying):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
# DEFAULT_FROM_EMAIL = 'ShopEase <noreply@shopease.com>'

# ==========================================
# TWILIO SMS CONFIGURATION (OTP)
# ==========================================

# Twilio credentials for sending SMS OTP
# Get from: https://www.twilio.com/console
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='')

# Check if Twilio is configured
TWILIO_ENABLED = bool(TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN and TWILIO_PHONE_NUMBER)

# Development: Print OTPs to console
# Production: Send real SMS via Twilio
if DEBUG and not TWILIO_ENABLED:
    print("\n" + "="*60)
    print("TWILIO NOT CONFIGURED - OTPs will print to console")
    print("="*60 + "\n")
    
# Razorpay Configuration
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')
RAZORPAY_MERCHANT_NAME = config('RAZORPAY_MERCHANT_NAME', default='ShopEase')

# Email Configuration
# Use real SMTP if credentials are provided, otherwise use console backend
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    # Real email sending (Gmail SMTP)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = True
else:
    # Development mode - print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@shopease.com')
ADMIN_EMAIL = config('ADMIN_EMAIL', default='admin@shopease.com')

# Currency Configuration
DEFAULT_CURRENCY = 'INR'
CURRENCY_SYMBOL = '₹'
DEFAULT_TAX_RATE = 0.18  # 18% GST

# Shipping Configuration
SHIPPING_COST = 50.00
FREE_SHIPPING_THRESHOLD = 1000.00

# config/settings.py

# Production settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Set ALLOWED_HOSTS
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
else:
    ALLOWED_HOSTS = [
        'yoursite.com',
        'www.yoursite.com',
    ]