"""
Django settings for shopease_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
"""
Django settings for shopease_project project.
===============================================

This file contains all the configuration for your Django project.
Think of it as the control panel for your entire application.

Generated by 'django-admin startproject' using Django 5.x.
"""

from pathlib import Path
import os

# BUILD PATHS INSIDE THE PROJECT
# ================================
# BASE_DIR points to the root folder of your project
# We use Path to handle file paths in a way that works on Windows, Mac, and Linux
# __file__ is this settings.py file
# .resolve() makes it an absolute path
# .parent.parent goes up two levels to get to project root
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY SETTINGS
# ==================
# SECRET_KEY: Used for cryptographic signing (sessions, passwords, etc.)
# NEVER share this key publicly! Change it in production!
SECRET_KEY = 'django-insecure-your-secret-key-change-this-in-production-12345'

# DEBUG: When True, Django shows detailed error pages
# ALWAYS set to False in production for security!
DEBUG = True

# ALLOWED_HOSTS: List of domains that can access your site
# Empty list means only localhost is allowed (good for development)
# In production, add your domain like: ['www.shopease.com', 'shopease.com']
ALLOWED_HOSTS = []


# APPLICATION DEFINITION
# =======================
# INSTALLED_APPS: All the Django apps that make up your project
# Django comes with built-in apps (admin, auth, etc.)
# We add our custom apps at the bottom

INSTALLED_APPS = [
    # DJANGO'S BUILT-IN APPS
    # -----------------------
    'django.contrib.admin',          # Admin interface at /admin/
    'django.contrib.auth',           # User authentication system
    'django.contrib.contenttypes',   # Content type system
    'django.contrib.sessions',       # Session framework (remembers users)
    'django.contrib.messages',       # One-time notification messages
    'django.contrib.staticfiles',    # Serves CSS, JS, images
    
    # OUR CUSTOM APPS
    # ----------------
    'accounts',      # User management, login, registration
    'products',      # Products, categories, images
    'cart',          # Shopping cart functionality
    'orders',        # Order processing and history
]


# MIDDLEWARE
# ===========
# Middleware are like security guards that process every request/response
# They run in order from top to bottom for requests
# And bottom to top for responses

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',       # Security enhancements
    'django.contrib.sessions.middleware.SessionMiddleware', # Enables sessions
    'django.middleware.common.CommonMiddleware',            # Common operations
    'django.middleware.csrf.CsrfViewMiddleware',           # Protection against CSRF attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Connects users to requests
    'django.contrib.messages.middleware.MessageMiddleware',    # Enables flash messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Prevents clickjacking attacks
]


# URL CONFIGURATION
# ==================
# ROOT_URLCONF: Points to the main urls.py file
# This is where Django starts looking for URL patterns
ROOT_URLCONF = 'shopease_project.urls'


# TEMPLATES CONFIGURATION
# ========================
# Templates are HTML files with Django template language
# This tells Django where to find them and how to process them

TEMPLATES = [
    {
        # DjangoTemplates: The template engine Django uses
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        # DIRS: Additional directories to search for templates
        # We add a 'templates' folder at project root for shared templates
        'DIRS': [BASE_DIR / 'templates'],
        
        # APP_DIRS: If True, Django looks for templates in each app's 'templates' folder
        'APP_DIRS': True,
        
        # OPTIONS: Additional settings for template processing
        'OPTIONS': {
            # context_processors: Functions that add variables to every template
            # These make things like 'user' and 'request' available in templates
            'context_processors': [
                'django.template.context_processors.debug',     # Adds debug info
                'django.template.context_processors.request',   # Adds request object
                'django.contrib.auth.context_processors.auth',  # Adds user info
                'django.contrib.messages.context_processors.messages', # Adds messages
                'django.template.context_processors.media',     # Adds MEDIA_URL
                'django.template.context_processors.static',    # Adds STATIC_URL
            ],
        },
    },
]


# WSGI CONFIGURATION
# ===================
# WSGI: Web Server Gateway Interface
# This is how web servers communicate with Python applications
WSGI_APPLICATION = 'shopease_project.wsgi.application'


# DATABASE CONFIGURATION
# =======================
# We're using SQLite for development (simple, file-based database)
# For production, switch to PostgreSQL or MySQL

DATABASES = {
    'default': {
        # Using SQLite (comes with Python, no installation needed)
        'ENGINE': 'django.db.backends.sqlite3',
        
        # Database file location (db.sqlite3 in project root)
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# For production, use PostgreSQL instead:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'shopease_db',
#         'USER': 'your_username',
#         'PASSWORD': 'your_password',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# PASSWORD VALIDATION
# ====================
# These validators ensure users create strong passwords
# They run when users register or change passwords

AUTH_PASSWORD_VALIDATORS = [
    {
        # Checks if password is too similar to user's other information
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Ensures password has minimum length (default: 8 characters)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # Checks if password is in list of common passwords
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Ensures password isn't entirely numeric
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# CUSTOM USER MODEL
# ==================
# We're using a custom User model instead of Django's default
# This gives us flexibility to add fields like 'role' for admin/customer
# IMPORTANT: This must be set BEFORE first migration!
AUTH_USER_MODEL = 'accounts.User'


# INTERNATIONALIZATION
# =====================
# Settings for language and timezone

# LANGUAGE_CODE: Default language for the site
LANGUAGE_CODE = 'en-us'

# TIME_ZONE: Timezone for storing dates in database
# Use your local timezone (e.g., 'Asia/Kolkata', 'America/New_York')
TIME_ZONE = 'UTC'

# USE_I18N: Enable Django's translation system
USE_I18N = True

# USE_TZ: Store datetimes in UTC in database (recommended)
USE_TZ = True


# STATIC FILES (CSS, JavaScript, Images)
# =======================================
# Static files are files that don't change (CSS, JS, logos, etc.)

# STATIC_URL: URL prefix for static files
# When you use {% static 'css/style.css' %} in templates,
# it becomes '/static/css/style.css'
STATIC_URL = '/static/'

# STATICFILES_DIRS: Additional directories to search for static files
# We create a 'static' folder at project root for shared files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# STATIC_ROOT: Where 'collectstatic' command collects all static files
# Used in production to serve static files efficiently
STATIC_ROOT = BASE_DIR / 'staticfiles'


# MEDIA FILES (User Uploads)
# ============================
# Media files are user-uploaded files (product images, avatars, etc.)

# MEDIA_URL: URL prefix for media files
# Product images will be accessible at '/media/products/image.jpg'
MEDIA_URL = '/media/'

# MEDIA_ROOT: Actual directory where uploaded files are stored
MEDIA_ROOT = BASE_DIR / 'media'


# DEFAULT PRIMARY KEY FIELD TYPE
# ================================
# This sets the default type for auto-generated ID fields
# BigAutoField can handle more records than regular AutoField
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# SESSION CONFIGURATION
# ======================
# Sessions store data about users between requests (shopping cart, etc.)

# SESSION_ENGINE: How to store session data
# Default uses database, but we can use cache for better performance
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# SESSION_COOKIE_AGE: How long session lasts (in seconds)
# 1209600 seconds = 14 days
SESSION_COOKIE_AGE = 1209600

# SESSION_SAVE_EVERY_REQUEST: Save session on every request
# Useful for keeping shopping cart updated
SESSION_SAVE_EVERY_REQUEST = False


# EMAIL CONFIGURATION (For Order Confirmations, Password Reset)
# ===============================================================
# For development, we'll just print emails to console
# In production, configure a real email service (Gmail, SendGrid, etc.)

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production with Gmail:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
# DEFAULT_FROM_EMAIL = 'ShopEase <noreply@shopease.com>'


# LOGIN/LOGOUT URLS
# ==================
# Where to redirect users after login/logout

# LOGIN_URL: Where to send users who need to log in
LOGIN_URL = 'accounts:login'

# LOGIN_REDIRECT_URL: Where to send users after successful login
LOGIN_REDIRECT_URL = 'home'

# LOGOUT_REDIRECT_URL: Where to send users after logout
LOGOUT_REDIRECT_URL = 'home'


# CART CONFIGURATION
# ===================
# Session key for storing cart data
CART_SESSION_ID = 'cart'


# MESSAGES CONFIGURATION
# =======================
# Configure how flash messages are displayed
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',  # Bootstrap uses 'danger' for errors
}


# SECURITY SETTINGS (For Production)
# ====================================
# Uncomment these when deploying to production

# SECURE_SSL_REDIRECT = True           # Force HTTPS
# SESSION_COOKIE_SECURE = True         # Send session cookie over HTTPS only
# CSRF_COOKIE_SECURE = True            # Send CSRF cookie over HTTPS only
# SECURE_BROWSER_XSS_FILTER = True     # Enable browser's XSS filter
# SECURE_CONTENT_TYPE_NOSNIFF = True   # Prevent MIME type sniffing
# X_FRAME_OPTIONS = 'DENY'             # Prevent site from being in iframe


print("✅ Settings loaded successfully!")
print(f"📁 Project directory: {BASE_DIR}")
print(f"🗄️  Database: {DATABASES['default']['NAME']}")
print(f"🎨 Static files URL: {STATIC_URL}")
print(f"📷 Media files URL: {MEDIA_URL}")