# Generated by Django 5.2.4 on 2026-01-13 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ORDER_STATUS_CHANGE', 'Changed Order Status'), ('REFUND_PROCESSED', 'Processed Refund'), ('PRODUCT_UPDATED', 'Updated Product'), ('FEATURED_CHANGED', 'Changed Featured Products'), ('REVIEW_MODERATED', 'Moderated Review'), ('ROLE_ASSIGNED', 'Assigned Role'), ('BULK_ACTION', 'Performed Bulk Action'), ('USER_CREATED', 'Created User'), ('USER_UPDATED', 'Updated User'), ('INVOICE_GENERATED', 'Generated Invoice')], db_index=True, help_text='Type of action performed', max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('order_id', models.UUIDField(blank=True, help_text='Related order ID (if applicable)', null=True)),
                ('product_id', models.PositiveIntegerField(blank=True, help_text='Related product ID (if applicable)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the admin user', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action was performed')),
                ('user', models.ForeignKey(help_text='Admin user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity',
                'verbose_name_plural': 'Admin Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='admin_panel_user_id_b202c8_idx'), models.Index(fields=['action', '-timestamp'], name='admin_panel_action_d8fbf9_idx'), models.Index(fields=['-timestamp'], name='admin_panel_timesta_c8ebd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CUSTOMER_SERVICE', 'Customer Service'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('MARKETING_MANAGER', 'Marketing Manager'), ('ORDER_MANAGER', 'Order Manager'), ('SUPER_ADMIN', 'Super Admin')], help_text='Role type determines default permissions', max_length=30)),
                ('can_view_orders', models.BooleanField(default=False, help_text='Can view order list and details')),
                ('can_edit_orders', models.BooleanField(default=False, help_text='Can change order status and add notes')),
                ('can_process_refunds', models.BooleanField(default=False, help_text='Can approve and process refund requests')),
                ('can_view_products', models.BooleanField(default=False, help_text='Can view product list and analytics')),
                ('can_edit_products', models.BooleanField(default=False, help_text='Can edit products and manage inventory')),
                ('can_manage_featured', models.BooleanField(default=False, help_text='Can select/modify featured products')),
                ('can_moderate_reviews', models.BooleanField(default=False, help_text='Can approve/reject customer reviews')),
                ('can_view_users', models.BooleanField(default=False, help_text='Can view user list and profiles')),
                ('can_manage_roles', models.BooleanField(default=False, help_text='Can assign roles to staff users')),
                ('can_view_analytics', models.BooleanField(default=False, help_text='Can access analytics and reports')),
                ('can_export_data', models.BooleanField(default=False, help_text='Can export data to CSV/Excel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Staff user assigned to this role', on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'indexes': [models.Index(fields=['user', 'role'], name='admin_panel_user_id_11cb0e_idx')],
            },
        ),
    ]
