# Generated by Django 5.2.4 on 2026-01-14 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique refund identifier', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount', max_digits=10)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item Received'), ('NOT_AS_DESCRIBED', 'Not As Described'), ('CHANGED_MIND', 'Changed Mind'), ('DAMAGED', 'Damaged in Shipping'), ('OTHER', 'Other')], help_text='Reason for refund', max_length=20)),
                ('description', models.TextField(help_text='Detailed explanation for the refund')),
                ('status', models.CharField(choices=[('REQUESTED', 'Refund Requested'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='REQUESTED', help_text='Current status of refund', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to customer)')),
                ('return_requested', models.BooleanField(default=False, help_text='Whether customer needs to return the product')),
                ('return_received', models.BooleanField(default=False, help_text='Whether returned product has been received')),
                ('restore_stock', models.BooleanField(default=True, help_text='Restore product stock when refund is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When refund was approved/rejected', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When refund was completed', null=True)),
                ('order', models.ForeignKey(help_text='Order associated with this refund', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='admin_panel_order_i_6ebe40_idx'), models.Index(fields=['status', '-created_at'], name='admin_panel_status_7071ce_idx'), models.Index(fields=['-created_at'], name='admin_panel_created_d794f0_idx')],
            },
        ),
    ]
