# Generated by Django 5.2.4 on 2026-01-14 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_refund'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MANUAL', 'Manually Selected'), ('AUTO', 'Auto-suggested')], default='MANUAL', help_text='How this product was featured', max_length=10)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0, help_text='Display priority (lower = higher priority)')),
                ('reason', models.TextField(blank=True, help_text='Why this product is featured (internal notes)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this feature is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-remove from featured after this date', null=True)),
                ('added_by', models.ForeignKey(help_text='Admin who featured this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_selections', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(help_text='Featured product', on_delete=django.db.models.deletion.CASCADE, related_name='featured_entry', to='products.product')),
            ],
            options={
                'verbose_name': 'Featured Product',
                'verbose_name_plural': 'Featured Products',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='admin_panel_is_acti_79fef1_idx'), models.Index(fields=['expires_at'], name='admin_panel_expires_26458c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of these analytics')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Total page views for this day')),
                ('unique_viewers', models.PositiveIntegerField(default=0, help_text='Unique visitors (by user or session)')),
                ('add_to_cart_count', models.PositiveIntegerField(default=0, help_text='Times added to cart')),
                ('wishlist_count', models.PositiveIntegerField(default=0, help_text='Times added to wishlist')),
                ('purchase_count', models.PositiveIntegerField(default=0, help_text='Number of times purchased')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Revenue generated from this product', max_digits=12)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average customer rating', max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Total number of reviews')),
                ('featured_score', models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Calculated score for auto-featuring (0-100)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product these analytics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Analytics',
                'verbose_name_plural': 'Product Analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', '-featured_score'], name='admin_panel_date_f3dcdc_idx'), models.Index(fields=['product', '-date'], name='admin_panel_product_4171f8_idx'), models.Index(fields=['-featured_score'], name='admin_panel_feature_dd2446_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProductEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40, null=True)),
                ('action', models.CharField(choices=[('ADD_TO_CART', 'Added to Cart'), ('ADD_TO_WISHLIST', 'Added to Wishlist'), ('REMOVE_FROM_CART', 'Removed from Cart'), ('REMOVE_FROM_WISHLIST', 'Removed from Wishlist')], db_index=True, help_text='Type of engagement action', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('product', models.ForeignKey(help_text='Product being interacted with', on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='products.product')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed action (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Engagement',
                'verbose_name_plural': 'Product Engagements',
                'indexes': [models.Index(fields=['product', 'action', '-timestamp'], name='admin_panel_product_d033e5_idx'), models.Index(fields=['-timestamp'], name='admin_panel_timesta_a06908_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of viewer', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string', max_length=255)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the product was viewed')),
                ('product', models.ForeignKey(help_text='Product that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product View',
                'verbose_name_plural': 'Product Views',
                'indexes': [models.Index(fields=['product', '-viewed_at'], name='admin_panel_product_fa33ef_idx'), models.Index(fields=['-viewed_at'], name='admin_panel_viewed__5b8b8d_idx'), models.Index(fields=['user', '-viewed_at'], name='admin_panel_user_id_ddf388_idx')],
            },
        ),
    ]
