# Generated by Django 5.2.4 on 2026-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_featuredproduct_productanalytics_productengagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='custom_role_name',
            field=models.CharField(blank=True, help_text='Name of the custom role', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='is_custom_role',
            field=models.BooleanField(default=False, help_text='True if this is a custom-created role'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='role_description',
            field=models.TextField(blank=True, help_text='Description of what this role does', null=True),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='role',
            field=models.CharField(blank=True, choices=[('CUSTOMER_SERVICE', 'Customer Service'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('MARKETING_MANAGER', 'Marketing Manager'), ('ORDER_MANAGER', 'Order Manager'), ('SUPER_ADMIN', 'Super Admin')], help_text='Role type determines default permissions (blank for custom roles)', max_length=30, null=True),
        ),
    ]
