# Generated by Django 5.2.4 on 2026-01-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_adminrole_custom_role_name_adminrole_is_custom_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='can_access_code_docs',
            field=models.BooleanField(default=False, help_text='Can view code-level explanations (superuser only)'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_edit_documentation',
            field=models.BooleanField(default=False, help_text='Can create/edit documentation'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_faqs',
            field=models.BooleanField(default=False, help_text='Can manage FAQ entries'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_versions',
            field=models.BooleanField(default=False, help_text='Can manage app versions and release notes'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_participate_dev_chat',
            field=models.BooleanField(default=False, help_text='Can participate in developer discussions'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_view_documentation',
            field=models.BooleanField(default=False, help_text='Can view documentation admin panel'),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='role',
            field=models.CharField(blank=True, choices=[('CUSTOMER_SERVICE', 'Customer Service'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('MARKETING_MANAGER', 'Marketing Manager'), ('ORDER_MANAGER', 'Order Manager'), ('SUPER_ADMIN', 'Super Admin'), ('DEVELOPER', 'Developer')], help_text='Role type determines default permissions (blank for custom roles)', max_length=30, null=True),
        ),
    ]
