# Generated by Django 6.0 on 2025-12-20 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Electronics', 'Clothing')", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('image', models.ImageField(blank=True, help_text='Category banner image', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this category from customers')),
                ('order', models.IntegerField(default=0, help_text='Display order (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name as shown to customers', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of name (auto-generated)', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('short_description', models.CharField(blank=True, help_text='Brief description shown in product cards', max_length=300)),
                ('price', models.DecimalField(decimal_places=2, help_text='Regular price', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price (leave empty if not on sale)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.IntegerField(default=0, help_text='Quantity in stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Warn when stock falls below this number')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit - unique product code', max_length=50, unique=True)),
                ('brand', models.CharField(blank=True, help_text='Product brand or manufacturer', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Active products are visible to customers')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured products appear on homepage')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, help_text='Average customer rating (0-5 stars)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0, help_text='Number of customer reviews')),
                ('total_sales', models.IntegerField(default=0, help_text='Total units sold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product image file', upload_to='products/')),
                ('alt_text', models.CharField(blank=True, help_text='Image description for accessibility and SEO', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image shows in product listings')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='products_pr_is_feat_a1ecf6_idx'),
        ),
    ]
