# Generated by Django 5.2.4 on 2025-12-30 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Electronics, Clothing)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of name (auto-generated)', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what products belong in this category', null=True)),
                ('image', models.ImageField(blank=True, help_text='Category thumbnail image', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this category visible on the website?')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name shown to customers', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version (auto-generated from name)', max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Brief description (shown in product cards)', max_length=300, null=True)),
                ('description', models.TextField(help_text='Full product description with all details')),
                ('price', models.DecimalField(decimal_places=2, help_text='Regular price in your currency', max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (leave empty if no sale)', max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0, help_text='Number of units available')),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Alert when stock drops below this number')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (unique product code)', max_length=100, null=True, unique=True)),
                ('brand', models.CharField(blank=True, help_text='Brand or manufacturer name', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is product visible on website?')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage and featured sections?')),
                ('average_rating', models.FloatField(default=0.0, help_text='Average customer rating (calculated from reviews)')),
                ('review_count', models.IntegerField(default=0, help_text='Total number of customer reviews')),
                ('views', models.IntegerField(default=0, help_text='Number of times product page was viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product photo (recommended: 800x800px or larger)', upload_to='products/')),
                ('alt_text', models.CharField(blank=True, help_text='Description for accessibility and SEO', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the main product image?')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Which product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
    ]
