# Generated by Django 5.2.4 on 2026-01-22 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text="Semantic versioning (e.g., '1.2.3')", max_length=20, unique=True)),
                ('version_type', models.CharField(choices=[('MAJOR', 'Major Release'), ('MINOR', 'Minor Release'), ('PATCH', 'Patch/Hotfix')], max_length=10)),
                ('release_date', models.DateField()),
                ('release_notes', models.TextField(help_text='Overall release notes (supports Markdown)')),
                ('new_features', models.TextField(blank=True, help_text='List of new features (one per line or Markdown list)')),
                ('bug_fixes', models.TextField(blank=True, help_text='List of bug fixes')),
                ('improvements', models.TextField(blank=True, help_text='List of improvements')),
                ('breaking_changes', models.TextField(blank=True, help_text='Breaking changes that require action')),
                ('is_current', models.BooleanField(default=False, help_text='Mark as current version (only one should be current)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'db_table': 'documentation_appversion',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyIssueHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_type', models.CharField(choices=[('ACCOUNT', 'Account Issues'), ('ORDER', 'Order Issues'), ('PAYMENT', 'Payment Issues'), ('PRODUCT', 'Product Issues'), ('TECHNICAL', 'Technical Issues'), ('OTHER', 'Other')], max_length=20)),
                ('problem_description', models.TextField(help_text='Describe the problem')),
                ('solution_steps', models.TextField(help_text='Step-by-step solution')),
                ('screenshot', models.ImageField(blank=True, help_text='Optional screenshot showing the issue or solution', null=True, upload_to='issue_help_screenshots/')),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('CUSTOMER', 'Customers Only'), ('ADMIN', 'Admins Only'), ('SUPERUSER', 'Superusers Only')], default='ALL', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Issue Help',
                'verbose_name_plural': 'Daily Issue Help',
                'db_table': 'documentation_dailyissuehelp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue_type'], name='documentati_issue_t_0274c2_idx'), models.Index(fields=['audience', 'is_active'], name='documentati_audienc_9bf1f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeveloperDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Thread description or initial question')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'bug, authentication, urgent')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Developer Discussion',
                'verbose_name_plural': 'Developer Discussions',
                'db_table': 'documentation_developerdiscussion',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='developer_chat/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='documentation.developerdiscussion')),
            ],
            options={
                'verbose_name': 'Developer Message',
                'verbose_name_plural': 'Developer Messages',
                'db_table': 'documentation_developermessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class (e.g., 'bi-book')", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='documentation.doccategory')),
            ],
            options={
                'verbose_name': 'Documentation Category',
                'verbose_name_plural': 'Documentation Categories',
                'db_table': 'documentation_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('content', models.TextField(help_text='Main documentation content (supports Markdown and HTML)')),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('CUSTOMER', 'Customers Only'), ('ADMIN', 'Admins Only'), ('SUPERUSER', 'Superusers Only')], default='ALL', max_length=20)),
                ('is_published', models.BooleanField(default=False, help_text='Published docs are visible to users')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on documentation homepage')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_docs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documentation.doccategory')),
            ],
            options={
                'verbose_name': 'Documentation',
                'verbose_name_plural': 'Documentation',
                'db_table': 'documentation_documentation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('module', models.CharField(choices=[('ACCOUNTS', 'Accounts App'), ('PRODUCTS', 'Products App'), ('ORDERS', 'Orders App'), ('CART', 'Cart App'), ('ADMIN_PANEL', 'Admin Panel'), ('CORE', 'Core App'), ('DOCUMENTATION', 'Documentation App')], max_length=20)),
                ('file_path', models.CharField(help_text="Relative path to file (e.g., 'shopease/apps/accounts/views.py')", max_length=500)),
                ('line_numbers', models.CharField(blank=True, help_text="Line range (e.g., '145-178')", max_length=50)),
                ('code_snippet', models.TextField(help_text='The actual code being explained')),
                ('explanation', models.TextField(help_text='Detailed line-by-line or block-by-block explanation')),
                ('why_it_matters', models.TextField(blank=True, help_text='Why this code pattern is important')),
                ('complexity', models.CharField(choices=[('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_docs', models.ManyToManyField(blank=True, related_name='related_code_examples', to='documentation.documentation')),
            ],
            options={
                'verbose_name': 'Code Explanation',
                'verbose_name_plural': 'Code Explanations',
                'db_table': 'documentation_codeexplanation',
                'ordering': ['module', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('CUSTOMER', 'Customers Only'), ('ADMIN', 'Admins Only'), ('SUPERUSER', 'Superusers Only')], default='ALL', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='documentation.doccategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'documentation_faq',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['slug'], name='documentati_slug_d1ec3b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['audience', 'is_published'], name='documentati_audienc_791cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['-created_at'], name='documentati_created_40477f_idx'),
        ),
        migrations.AddIndex(
            model_name='codeexplanation',
            index=models.Index(fields=['slug'], name='documentati_slug_de617c_idx'),
        ),
        migrations.AddIndex(
            model_name='codeexplanation',
            index=models.Index(fields=['module'], name='documentati_module_9ac0e7_idx'),
        ),
    ]
